language: python
sudo: false
cache: pip

python:
  - 3.6

matrix:
  include:
    # Python 3.7 workaround
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7.2
      dist: xenial
      sudo: true

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install -U pylama
  - pip install -U -r requirements.txt

before_script:
  # The config file won't actually be used during CI builds,
  # but we have to prevent launch.py from throwing an error
  # due to a missing config.yaml file.
  - cp config.example.yaml config.yaml
  - psql -c "CREATE ROLE ci WITH LOGIN SUPERUSER;" -U postgres
  - psql -c "CREATE DATABASE code_inspector OWNER ci;" -U postgres

script:
  - pylama .
  - python launch.py --stream-log